# Generated by Django 5.1.6 on 2025-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=65535)),
                ('company', models.CharField(max_length=65535)),
                ('date', models.CharField(max_length=65535)),
                ('band', models.CharField(max_length=65535)),
                ('bandwidth', models.CharField(max_length=65535)),
                ('address', models.CharField(max_length=65535)),
                ('district', models.CharField(max_length=65535)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('voice_connection', models.FloatField()),
                ('voice_traffic', models.FloatField()),
                ('data_connection', models.FloatField()),
                ('data_traffic', models.FloatField()),
            ],
        ),
    ]
