# Generated by Django 5.1.6 on 2025-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_celldata_address_alter_celldata_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldata',
            name='cell_id',
            field=models.BinaryField(),
        ),
    ]
