# Generated by Django 5.1.6 on 2025-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_celldata_cell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldata',
            name='cell_id',
            field=models.TextField(),
        ),
    ]
