# Generated by Django 5.1.6 on 2025-02-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_celldata_cell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldata',
            name='cell_id',
            field=models.CharField(max_length=255),
        ),
    ]
